# Generated by Django 4.2.3 on 2023-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_customer_rename_credit_companies_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
