# Generated by Django 4.2.3 on 2023-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='type',
            field=models.CharField(default=0, max_length=170),
        ),
        migrations.AlterField(
            model_name='qr',
            name='qr',
            field=models.CharField(default=0, max_length=170),
        ),
    ]
