# Generated by Django 4.2.3 on 2023-10-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_remove_qr_current_date_qr_qr_qr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='pub_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
