# Generated by Django 4.2.3 on 2023-09-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0002_qr_type_alter_qr_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='qr',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='qr',
            name='type',
            field=models.CharField(max_length=170),
        ),
    ]
