# Generated by Django 4.2.3 on 2023-09-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_alter_qr_qr_alter_qr_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
