# Generated by Django 4.2.3 on 2023-10-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0003_qr_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='pub_date',
        ),
    ]
