# Generated by Django 4.2.3 on 2023-10-05 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0004_remove_qr_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
