# Generated by Django 4.2.3 on 2023-09-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0004_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
