# Generated by Django 4.2.3 on 2023-10-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_alter_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
