# Generated by Django 4.2.3 on 2023-10-05 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0005_qr_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='qr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
