# Generated by Django 4.2.3 on 2023-10-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_app', '0007_alter_qr_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
