# Generated by Django 4.2.3 on 2023-08-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_money'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='Operation',
        ),
    ]
