# Generated by Django 4.2.3 on 2023-12-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='selected_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
