# Generated by Django 4.2.3 on 2023-08-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='full_name',
        ),
    ]
