# Generated by Django 4.2.3 on 2023-08-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_loginuser_email_remove_loginuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
    ]
