# Generated by Django 4.2.3 on 2023-09-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tweet_delete_loginuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
