# Generated by Django 4.2.3 on 2023-08-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseapp', '0002_websiteayarlari_nav_item_websiteayarlari_nav_item4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_item', models.CharField(default=1, max_length=50)),
                ('nav_item_2', models.CharField(default=1, max_length=50)),
                ('nav_item_3', models.CharField(default=1, max_length=50)),
                ('nav_item4', models.CharField(default=1, max_length=50)),
                ('nav_item5', models.CharField(default=1, max_length=50)),
                ('nav_item6', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='websiteayarlari',
            name='nav_item',
        ),
        migrations.RemoveField(
            model_name='websiteayarlari',
            name='nav_item4',
        ),
        migrations.RemoveField(
            model_name='websiteayarlari',
            name='nav_item5',
        ),
        migrations.RemoveField(
            model_name='websiteayarlari',
            name='nav_item6',
        ),
        migrations.RemoveField(
            model_name='websiteayarlari',
            name='nav_item_2',
        ),
        migrations.RemoveField(
            model_name='websiteayarlari',
            name='nav_item_3',
        ),
    ]
