# Generated by Django 4.2.3 on 2023-08-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseapp', '0003_items_remove_websiteayarlari_nav_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='nav_item_2',
            new_name='nav_item2',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='nav_item_3',
            new_name='nav_item3',
        ),
        migrations.AlterField(
            model_name='websiteayarlari',
            name='collapse_text',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
