# Generated by Django 4.2.3 on 2023-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseapp', '0008_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(default=1, max_length=50)),
            ],
        ),
    ]
